CREATE TABLE company (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10001) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    legal_address VARCHAR(255) NOT NULL,
    fact_address VARCHAR(255) NOT NULL
);

CREATE TABLE industry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10001) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10001) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    position VARCHAR(255) NOT NULL,
    company_id BIGINT NOT NULL REFERENCES company(id)
);

CREATE TABLE subsidy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10001) PRIMARY KEY,
    requested_subsidy NUMERIC(19, 2) NOT NULL CHECK (requested_subsidy > 0),
    approved_subsidy NUMERIC(19, 2) NOT NULL CHECK (approved_subsidy >= 0 AND approved_subsidy <= requested_subsidy),
    industry_id BIGINT NOT NULL REFERENCES industry(id),
    company_id BIGINT NOT NULL REFERENCES company(id),
    person_in_charge_id BIGINT NOT NULL REFERENCES employee(id)
);

CREATE INDEX idx_employee_company ON employee(company_id);
CREATE INDEX idx_subsidy_company ON subsidy(company_id);
CREATE INDEX idx_subsidy_industry ON subsidy(industry_id);
CREATE INDEX idx_subsidy_person_in_charge ON subsidy(person_in_charge_id);
